owner: dev-okticket
repo: status

sites:
  - name: OKTicket
    url: https://www.okticket.es
  - name: Gestor OKTicket
    url: https://admin.okticket.es/
  - name: Gestor Nuevo
    url: https://adminokt.okticket.es/
  - name: BBDD Mongo
    url: https://api.okticket.es/v2/public/api/monitor/mongodb
  - name: BBDD Mysql
    url: https://api.okticket.es/v2/public/api/monitor/mysql
  - name: Test OKTicket Gestor
    url: http://15.237.124.134



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://adminokt.okticket.es/img/logo-okticket-blue.d2d4fb49.png
  name: SACA UNA FOTO, TIRA EL TICKET
  introTitle: " **OKTicket**  status page."
  introMessage: .
