owner: dev-okticket
repo: status

sites:
  - name: OKTicket
    url: https://www.okticket.es
  - name: Gestor OKTicket
    url: https://admin.okticket.es/
  - name: Gestor Nuevo
    url: https://adminokt.okticket.es/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://adminokt.okticket.es/img/logo-okticket-blue.d2d4fb49.png
  name: status
  introTitle: " **OKTicket**  status page."
  introMessage: .
  navbar:
    - title: SACA UNA FOTO, TIRA EL TICKET 
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

